version: "2"
services:
    font-end:
        image: front-end
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./front-end:/front-end
            - /font-end/node_modules
        links:
            - back-end
        networks:
            - webappnetwork
    back-end:
        image: back-end
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./back-end:/back-end
            - /back-end/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge